# Generated by Django 4.0.1 on 2022-02-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_alter_inheritance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetype',
            options={'verbose_name': 'Place type', 'verbose_name_plural': 'Place types'},
        ),
        migrations.AlterField(
            model_name='places',
            name='Description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='places',
            name='Type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='Places.placetype', verbose_name='place type'),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='Name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
