# Generated by Django 4.0.1 on 2022-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_alter_placetype_options_alter_places_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='Description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
